apiVersion: apps/v1
kind: Deployment
metadata:
  name: hariwebapi-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hariwebapi-depl
  template:
    metadata:
      labels:
        app: hariwebapi-depl
    spec:
      containers:
      - name: hariwebapicontainer
        image: haridata23/webapiimage:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
