apiVersion: v1
kind: Service
metadata:
  name: demowebapi-service
spec:
  type: NodePort
  selector:
    app: demowebapi-service
  ports:
    - name: demowebapi
      protocol: TCP
      port: 80
      targetPort: 80
